### ISSUE TITLE
Kotlin multiplatform compatibility

### ISSUE THREAD

**Issue by Nek-12** [Andrew0000/Universal-Cache#1]
Basically, that's it: any plans to make the library KMM-compatible?

**Comment by Andrew0000** [comment]
Hi. It's a good idea, but I can't tell exact timeline for this change

**Comment by Andrew0000** [comment]
PR with migration to KMP + Maven Central: 
https://github.com/Andrew0000/Universal-Cache/pull/4 

You already can try it with this maven dependency: 
implementation("io.github.andrew0000:universal-cache:1.1.6")

**Comment by Andrew0000** [comment]
Released. Please drop a comment if something else is needed.
