### ISSUE TITLE
Does this work as a shared library for iOS + Android?

### ISSUE THREAD

**Issue by anox1337** [Andrew0000/Universal-Cache#5]
Hello!

`       val commonMain by getting {
            dependencies {
                implementation("io.github.andrew0000:universal-cache:1.1.6")

`

Trying to build results in the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':shared:iosSimulatorArm64CompileKlibraries'.
> Could not resolve io.github.andrew0000:universal-cache:1.1.6.
  Required by:
      project :shared
   > No matching variant of io.github.andrew0000:universal-cache:1.1.6 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' but:
       - Variant 'iosArm64ApiElements-published' capability io.github.andrew0000:universal-cache:1.1.6 declares a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
           - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
           - Other compatible attribute:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)`

Is this an error on my end or does not work with an ios build?

Cheers

**Comment by Andrew0000** [comment]
Hi @anox1337, probably the problem is on my side, I haven't released separate version of the library for IOS simulator.
By the way, could you please check if it works on real IOS device?

**Comment by Andrew0000** [comment]
Please try version 1.1.7 (may take a few hours to be indexed by maven). 
I added **iosSimulatorArm64** version, it should work.

**Comment by anox1337** [comment]
Appreciate the feedback! Just my Luck :'( My Apple Hardware is currently not available but I should have it back in about 2 weeks time. I will get back to you and thanks for looking into it

**Comment by anox1337** [comment]
Hi again.
1.1.7 works on the simulator and on a real device. 
Thank you!
